---
name: Publish Role on Ansible Galaxy
description: Publish an Ansible role on Ansible Galaxy
author: pako-23 <pasqualepolverino98@gmail.com>

branding:
  icon: package
  color: blue

inputs:
  token:
    description: >
      The Ansible Galaxy API key which can be found at
      https://galaxy.ansible.com/me/preferences.
    required: true

runs:
  using: node24
  main: dist/index.js
